global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # APISIX Gateway
  - job_name: 'apisix'
    static_configs:
      - targets: ['apisix:9091']
    metrics_path: /apisix/prometheus/metrics
    scrape_interval: 15s
    
  # Microservices
  - job_name: 'auth-service'
    static_configs:
      - targets: ['auth-service:8084']
    metrics_path: /actuator/prometheus
    scrape_interval: 15s
    
  - job_name: 'user-service'
    static_configs:
      - targets: ['user-service:8081']
    metrics_path: /actuator/prometheus
    scrape_interval: 15s
    
  - job_name: 'product-service'
    static_configs:
      - targets: ['product-service:8082']
    metrics_path: /actuator/prometheus
    scrape_interval: 15s
    
  - job_name: 'order-service'
    static_configs:
      - targets: ['order-service:8083']
    metrics_path: /actuator/prometheus
    scrape_interval: 15s
    
  - job_name: 'payment-service'
    static_configs:
      - targets: ['payment-service:8085']
    metrics_path: /actuator/prometheus
    scrape_interval: 15s
    
  # Infrastructure
  - job_name: 'mysql'
    static_configs:
      - targets: ['mysql:3306']
    scrape_interval: 30s
    
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
    scrape_interval: 30s
    
  - job_name: 'etcd'
    static_configs:
      - targets: ['etcd:2379']
    scrape_interval: 30s