apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: microservices
type: Opaque
data:
  # root:password (base64 encoded)
  username: cm9vdA==
  password: cGFzc3dvcmQ=
  root-password: cGFzc3dvcmQ=
---
apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: microservices
type: Opaque
data:
  # JWT secret key (base64 encoded)
  jwt-secret: bXlfc2VjcmV0X2p3dF9rZXk=
  # API keys and sensitive configs
  api-key: YXBpX2tleV9zZWNyZXQ=
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: microservices
data:
  # Database URLs
  auth-db-url: "jdbc:mysql://mysql:3306/auth_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true"
  user-db-url: "jdbc:mysql://mysql:3306/user_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true"
  product-db-url: "jdbc:mysql://mysql:3306/product_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true"
  order-db-url: "jdbc:mysql://mysql:3306/order_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true"
  payment-db-url: "jdbc:mysql://mysql:3306/payment_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true"
  
  # Service URLs
  user-service-url: "http://user-service:8081"
  product-service-url: "http://product-service:8082"
  order-service-url: "http://order-service:8083"
  auth-service-url: "http://auth-service:8084"
  payment-service-url: "http://payment-service:8085"
  
  # Application configs
  server-port: "8080"
  spring-profiles-active: "k8s"